# Generated by Django 5.2.12 on 2026-03-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('match_json', models.JSONField(help_text='Match criteria, e.g. {"field": "severity", "operator": "eq", "value": "critical"}')),
                ('priority', models.IntegerField(help_text='Lower number = evaluated first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='queues.queue')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
