# Generated by Django 5.2.12 on 2026-03-15 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('customer', 'Customer'), ('analyst', 'Analyst'), ('system', 'System')], max_length=20)),
                ('actor_id', models.CharField(help_text='UID of the customer, analyst, or system', max_length=255)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (customer → system)'), ('outbound', 'Outbound (system → customer)')], max_length=20)),
                ('source', models.CharField(choices=[('customer_api', 'Customer API'), ('roam_webhook', 'Roam Webhook'), ('internal', 'Internal System')], max_length=20)),
                ('external_message_id', models.CharField(blank=True, help_text='Message ID from Roam or external system', max_length=255, null=True)),
                ('body_plain', models.TextField()),
                ('body_markdown', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('system_note', 'System Note'), ('status', 'Status Update')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='idx_msg_conv_created')],
            },
        ),
    ]
