# Generated by Django 5.2.12 on 2026-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.CharField(choices=[('customer_api', 'Customer API'), ('roam_webhook', 'Roam Webhook'), ('internal', 'Internal System'), ('slack', 'Slack')], max_length=20),
        ),
    ]
