# Generated by Django 5.2.12 on 2026-10-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('slack', 'Slack')], max_length=20)),
                ('team_id', models.CharField(help_text='Workspace/tenant ID on the provider', max_length=64)),
                ('external_user_id', models.CharField(help_text='User ID on the provider', max_length=64)),
                ('org_id', models.CharField(db_index=True, max_length=100)),
                ('email', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('linked_user_id', models.CharField(blank=True, db_index=True, help_text='Cyflare ONE user ID once linked', max_length=255, null=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'team_id', 'external_user_id'), name='unique_external_identity')],
            },
        ),
    ]
