# Generated by Django 5.2.12 on 2026-03-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Unique slug identifier (e.g. soc-triage)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('priority_order', models.IntegerField(default=100, help_text='Lower number = higher priority for queue ordering')),
                ('sla_first_response_seconds', models.IntegerField(blank=True, null=True)),
                ('sla_resolution_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalystProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_user_id', models.CharField(help_text='Roam user ID or external identifier', max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysts', to='queues.queue')),
            ],
        ),
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_response_seconds', models.IntegerField(help_text='Max seconds to first analyst response')),
                ('resolution_seconds', models.IntegerField(help_text='Max seconds to resolution')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='queues.queue')),
            ],
            options={
                'verbose_name_plural': 'SLA policies',
            },
        ),
        migrations.CreateModel(
            name='QueueGroupMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('roam_group_id', models.CharField(help_text='Roam group/chat ID', max_length=255)),
                ('roam_group_name', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='queues.queue')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('queue', 'roam_group_id'), name='unique_queue_roam_group')],
            },
        ),
    ]
