# Generated by Django 5.2.12 on 2026-10-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackInstallation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(help_text='Slack workspace ID (T…)', max_length=32, unique=True)),
                ('team_name', models.CharField(blank=True, default='', max_length=255)),
                ('enterprise_id', models.CharField(blank=True, default='', help_text='Enterprise Grid ID (E…)', max_length=32)),
                ('org_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending (not yet linked to an org)'), ('active', 'Active'), ('inactive', 'Inactive (uninstalled or revoked)')], default='pending', max_length=20)),
                ('bot_user_id', models.CharField(blank=True, default='', max_length=32)),
                ('bot_token_encrypted', models.TextField(help_text='Fernet-encrypted bot token (xoxb-…)')),
                ('scopes', models.TextField(blank=True, default='')),
                ('installed_by_slack_user_id', models.CharField(blank=True, default='', max_length=32)),
                ('linked_by_user_id', models.CharField(blank=True, default='', help_text='Cyflare ONE user who linked the install to the org', max_length=255)),
                ('claim_code_hash', models.CharField(blank=True, default='', max_length=64)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
    ]
