# Generated by Django 5.2.12 on 2026-10-09 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_conversationparticipant'),
        ('integrations_slack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('is_im', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True, help_text='Disabled channels are ignored')),
                ('conversation_trigger', models.CharField(blank=True, default='', help_text="Overrides the org's conversation trigger when set (all_messages or emoji)", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='integrations_slack.slackinstallation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('installation', 'channel_id'), name='unique_slack_channel')],
            },
        ),
        migrations.CreateModel(
            name='SlackThread',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=32)),
                ('channel_id', models.CharField(max_length=32)),
                ('thread_ts', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_threads', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team_id', 'channel_id', 'thread_ts'], name='idx_slack_thread_lookup')],
            },
        ),
    ]
