# Generated by Django 5.2.12 on 2026-03-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('idempotency_key', models.CharField(help_text='Unique key to prevent duplicate processing', max_length=255, unique=True)),
                ('source', models.CharField(help_text='Origin of the event (e.g. customer_api, roam_webhook)', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation'], name='idx_eventlog_conversation'), models.Index(fields=['event_type', 'created_at'], name='idx_eventlog_type_created')],
            },
        ),
    ]
