# Generated by Django 5.2.12 on 2026-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, help_text='Customer org ID. Null = deployment-wide default.', max_length=100, null=True, unique=True)),
                ('severity_colors', models.JSONField(blank=True, default=dict, help_text='Partial map of severity level → Roam color value. e.g. {"critical": "danger", "high": "#F59E0B"}. Merged with defaults; only specified keys are overridden.')),
                ('header_text', models.CharField(blank=True, default='', help_text='Header block text for new conversations. Empty = use deployment default.', max_length=200)),
                ('fallback_color', models.CharField(blank=True, default='', help_text='Color for unknown severity levels. Empty = use deployment default.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branding config',
                'verbose_name_plural': 'Branding configs',
            },
        ),
    ]
