# Generated by Django 5.2.12 on 2026-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.CharField(help_text='Cyflare ONE organization ID', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('slack_allow_unlinked_users', models.BooleanField(default=True, help_text='Allow Slack users without a linked Cyflare ONE account to start conversations')),
                ('slack_merge_window_minutes', models.PositiveIntegerField(default=30, help_text='Top-level Slack posts from the same person within this window join their open conversation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
