# Generated by Django 5.2.12 on 2026-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slack_auto_join_pattern',
            field=models.CharField(blank=True, default='', help_text='Glob for public channel names the bot joins automatically, e.g. cyflare-*', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='slack_conversation_trigger',
            field=models.CharField(choices=[('all_messages', 'Every top-level message'), ('emoji', 'Only messages given the trigger emoji')], default='all_messages', help_text='What starts a conversation in a Slack channel (channels can override)', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='slack_trigger_emoji',
            field=models.CharField(default='speech_balloon', help_text="Reaction name used when the trigger is 'emoji'", max_length=64),
        ),
    ]
