# Generated by Django 5.2.12 on 2026-03-15 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_org_id', models.CharField(db_index=True, max_length=100)),
                ('customer_org_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_user_id', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.CharField(blank=True, default='', max_length=255)),
                ('source_channel', models.CharField(choices=[('mobile_ios', 'iOS Mobile App'), ('mobile_android', 'Android Mobile App'), ('web', 'Web')], default='mobile_ios', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('queued', 'Queued'), ('assigned', 'Assigned'), ('waiting_customer', 'Waiting on Customer'), ('waiting_soc', 'Waiting on SOC'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(blank=True, default='normal', max_length=20)),
                ('severity', models.CharField(blank=True, default='', max_length=20)),
                ('issue_category', models.CharField(blank=True, default='', max_length=100)),
                ('tier', models.CharField(blank=True, default='', max_length=50)),
                ('roam_thread_key', models.CharField(db_index=True, help_text='threadKey used in Roam API calls', max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='queues.analystprofile')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='queues.queue')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_by', models.CharField(help_text='ID of user who made the assignment', max_length=255)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='queues.analystprofile')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('applied_by', models.CharField(default='', max_length=255)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_tags', to='conversations.conversation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_tags', to='conversations.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['queue', 'status'], name='idx_conv_queue_status'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer_org_id', 'customer_user_id'], name='idx_conv_customer'),
        ),
        migrations.AddConstraint(
            model_name='conversationtag',
            constraint=models.UniqueConstraint(fields=('conversation', 'tag'), name='unique_conversation_tag'),
        ),
    ]
