# Generated by Django 5.2.12 on 2026-03-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='roam_thread_timestamp',
            field=models.BigIntegerField(blank=True, help_text='Roam threadTimestamp for polling chat.history replies', null=True),
        ),
    ]
