# Generated by Django 5.2.12 on 2026-03-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_add_roam_thread_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_user_id', models.CharField(max_length=255)),
                ('rating', models.SmallIntegerField(choices=[(1, 'Bad'), (2, 'OK'), (3, 'Great')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='conversations.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['customer_user_id'], name='idx_feedback_customer')],
            },
        ),
    ]
