# Generated by Django 5.2.12 on 2026-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_add_subject_to_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='source_channel',
            field=models.CharField(choices=[('mobile_ios', 'iOS Mobile App'), ('mobile_android', 'Android Mobile App'), ('web', 'Web'), ('slack', 'Slack')], default='mobile_ios', max_length=20),
        ),
    ]
