# Generated by Django 5.2.12 on 2026-10-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_alter_conversation_source_channel'),
        ('identities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='ONE user ID, or a synthetic ID such as slack:T…:U… until linked', max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='conversations.conversation')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='identities.externalidentity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user_id'), name='unique_conversation_participant')],
            },
        ),
    ]
